

services:
  db:  
    build: .
    container_name: volunteer-scheduler-db
    environment:
      POSTGRES_DB: volunteer-scheduler
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: /run/secrets/postgres_password
    ports:
      - "5433:5432"
    volumes:
      - volunteer-scheduler-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  postgres_password:
    file: ./secret_postgres_pw
  
volumes:
  volunteer-scheduler-data:
    driver: local
